### ISSUE TITLE
virt-manager "Could not detect a default hypervisor" on Rawhide

### ISSUE THREAD

**Issue by bluebluesilver** [fedora-silverblue/issue-tracker#165]
On Silverblue/Rawhide virt-manager doesn't work when I start it. Virtualisation is new to me, so please correct me if anything is wrong (eg terminology) or more info is needed.

## Steps to Reproduce
Start virt-manager. The following message appears in the virt-manager window.
> Could not detect a default hypervisor. Make sure the appropriate QEMU/KVM virtualization packages are installed to manage virtualization on this host.
> A virtualization connection can be manually added via File->Add Connection

### Following the Instructions
Add a connection manually (File -> Add Connection -> Connect), error:
```
Unable to connect to libvirt qemu:///system.
Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory
Libvirt URI is: qemu:///system
Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/connection.py", line 922, in _do_open
    self._backend.open(cb, data)
  File "/usr/share/virt-manager/virtinst/connection.py", line 153, in open
    conn = libvirt.openAuth(self._open_uri,
  File "/usr/lib64/python3.9/site-packages/libvirt.py", line 148, in openAuth
    raise libvirtError('virConnectOpenAuth() failed')
libvirt.libvirtError: Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory
```

## Expected Behaviour
No error, and I am able to create VMs

## Additional Information
```
$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/rawhide/x86_64/silverblue
                   Version: Rawhide.20210507.n.0 (2021-05-07T06:04:44Z)
                BaseCommit: e0b21f7f8830cb8e24c17d74fa1aed05b7b94beba497d5332fc581e5c7c3f017
              GPGSignature: Valid signature by 787EA6AE1147EEE56C40B30CDB4639719867C58F
           LayeredPackages: gnome-tweaks kitty kitty-terminfo virt-manager
--snip--

$ systemctl status libvirtd
○ libvirtd.service - Virtualization daemon
     Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2021-05-07 13:11:31 UTC; 8min ago
TriggeredBy: ● libvirtd-admin.socket
             ● libvirtd-ro.socket
             ● libvirtd.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
    Process: 22611 ExecStart=/usr/sbin/libvirtd $LIBVIRTD_ARGS (code=exited, status=0/SUCCESS)
   Main PID: 22611 (code=exited, status=0/SUCCESS)
      Tasks: 2 (limit: 32768)
     Memory: 9.3M
        CPU: 132ms
     CGroup: /system.slice/libvirtd.service
             ├─2147 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper
             └─2148 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/libexec/libvirt_leaseshelper

May 07 13:08:47 fedora dnsmasq-dhcp[2147]: read /var/lib/libvirt/dnsmasq/default.hostsfile
May 07 13:08:50 fedora libvirtd[22611]: libvirt version: 7.3.0, package: 1.fc35 (Fedora Project, 2021-05-04-11:00:25, )
May 07 13:08:50 fedora libvirtd[22611]: hostname: fedora
May 07 13:08:50 fedora libvirtd[22611]: Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory
May 07 13:08:50 fedora libvirtd[22611]: End of file while reading data: Input/output error
May 07 13:09:31 fedora libvirtd[22611]: Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory
May 07 13:09:31 fedora libvirtd[22611]: End of file while reading data: Input/output error
May 07 13:11:31 fedora systemd[1]: libvirtd.service: Deactivated successfully.
May 07 13:11:31 fedora systemd[1]: libvirtd.service: Unit process 2147 (dnsmasq) remains running after unit stopped.
May 07 13:11:31 fedora systemd[1]: libvirtd.service: Unit process 2148 (dnsmasq) remains running after unit stopped.
```

**Comment by bluebluesilver** [comment]
Tested on latest fedora34, and virt-manager works normally, no error.

```
$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/34/x86_64/silverblue
                   Version: 34.20210507.0 (2021-05-07T00:45:36Z)
                BaseCommit: a0ca5647b4c7cead00648c21d9ed42ef9ddaaca8303b3162223dbb8fe586ca71
              GPGSignature: Valid signature by 8C5BA6990BDB26E19F2A1A801161AE6945719A39
           LayeredPackages: kitty kitty-terminfo virt-manager
--snip--
```

**Comment by tpopela** [comment]
@felipeborges any idea?

**Comment by daniel-wtd** [comment]
Not sure if this helps, but I cannot reproduce this on my machine (silverblue, but not rawhide). User and system sessions are working fine, and user session is configured by default in virt-manager.

**Comment by travier** [comment]
Closing as this is likely stale and would need to be reproduced.
