### ISSUE TITLE
[BUG] [36] Composes failing on rpm-ostree compose tree

### ISSUE THREAD

**Issue by travier** [fedora-silverblue/issue-tracker#326]
See:
- https://pagure.io/releng/failed-composes/issue/3847
- https://pagure.io/releng/failed-composes/issue/3854

https://kojipkgs.fedoraproject.org//work/tasks/6126/90896126/root.log:
```
INFO backend.py:391:  Running in chroot: ['/bin/sh', '-c', "{ rm -f /var/lib/rpm/__db*; rm -rf /var/cache/yum/*; set -x; pungi-make-ostree tree --repo=/mnt/koji/compose/ostree/repo --log-dir=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4 --treefile=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/config_repo/fedora-kinoite.yaml --version=36.20220817.0 --extra-config=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/extra_config.json '--ostree-ref=fedora/36/${basearch}/updates/kinoite'; } < /dev/null 2>&1 | /usr/bin/tee /builddir/runroot.log; exit ${PIPESTATUS[0]}"]
DEBUG util.py:622:  child environment: None
DEBUG util.py:535:  Using nspawn with args ['--capability=cap_ipc_lock', '--bind=/tmp/mock-resolv.ekv80dli:/etc/resolv.conf', '--bind=/dev/btrfs-control', '--bind=/dev/loop-control', '--bind=/dev/loop0', '--bind=/dev/loop1', '--bind=/dev/loop2', '--bind=/dev/loop3', '--bind=/dev/loop4', '--bind=/dev/loop5', '--bind=/dev/loop6', '--bind=/dev/loop7', '--bind=/dev/loop8', '--bind=/dev/loop9', '--bind=/dev/loop10', '--bind=/dev/loop11']
DEBUG util.py:540:  Executing command: ['/usr/bin/systemd-nspawn', '-q', '-M', '3e3ff5b6dfcf49b0bbe05a67c45a96fc', '-D', '/var/lib/mock/f36-build-37456535-4769766/root', '-a', '--capability=cap_ipc_lock', '--bind=/tmp/mock-resolv.ekv80dli:/etc/resolv.conf', '--bind=/dev/btrfs-control', '--bind=/dev/loop-control', '--bind=/dev/loop0', '--bind=/dev/loop1', '--bind=/dev/loop2', '--bind=/dev/loop3', '--bind=/dev/loop4', '--bind=/dev/loop5', '--bind=/dev/loop6', '--bind=/dev/loop7', '--bind=/dev/loop8', '--bind=/dev/loop9', '--bind=/dev/loop10', '--bind=/dev/loop11', '--console=pipe', '--setenv=TERM=vt100', '--setenv=SHELL=/bin/bash', '--setenv=HOME=/builddir', '--setenv=HOSTNAME=mock', '--setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin', '--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"', '--setenv=PS1=<mock-chroot> \\s-\\v\\$ ', '--setenv=LANG=C.UTF-8', '--resolv-conf=off', '/bin/sh', '-c', "{ rm -f /var/lib/rpm/__db*; rm -rf /var/cache/yum/*; set -x; pungi-make-ostree tree --repo=/mnt/koji/compose/ostree/repo --log-dir=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4 --treefile=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/config_repo/fedora-kinoite.yaml --version=36.20220817.0 --extra-config=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/extra_config.json '--ostree-ref=fedora/36/${basearch}/updates/kinoite'; } < /dev/null 2>&1 | /usr/bin/tee /builddir/runroot.log; exit ${PIPESTATUS[0]}"] with env {'TERM': 'vt100', 'SHELL': '/bin/bash', 'HOME': '/builddir', 'HOSTNAME': 'mock', 'PATH': '/usr/bin:/bin:/usr/sbin:/sbin', 'PROMPT_COMMAND': 'printf "\\033]0;<mock-chroot>\\007"', 'PS1': '<mock-chroot> \\s-\\v\\$ ', 'LANG': 'C.UTF-8', 'SYSTEMD_NSPAWN_TMPFS_TMP': '0', 'SYSTEMD_SECCOMP': '0'} and shell False
DEBUG util.py:445:  + pungi-make-ostree tree --repo=/mnt/koji/compose/ostree/repo --log-dir=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4 --treefile=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/config_repo/fedora-kinoite.yaml --version=36.20220817.0 --extra-config=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/extra_config.json '--ostree-ref=fedora/36/${basearch}/updates/kinoite'
DEBUG util.py:445:  COMMAND: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo --write-commitid-to=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4/commitid.log --touch-if-changed=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4/commitid.log.stamp --add-metadata-string=version=36.20220817.0 /mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/config_repo/fedora-kinoite.json
DEBUG util.py:445:  -------------------------------------------------------------------------------
DEBUG util.py:445:  rpm-ostree version: 2022.12
DEBUG util.py:445:  Previous commit: 3ddbe834b41e05e70ae937b37588252643b095ee1bf5865c9c53761ddec65398
DEBUG util.py:445:  NOTICE: Running rpm-ostree compose tree without --unified-core is deprecated.
DEBUG util.py:445:   Please add --unified-core to the command line and ensure your content
DEBUG util.py:445:   works with it.  For more information, see https://github.com/coreos/rpm-ostree/issues/729
DEBUG util.py:445:  Enabled rpm-md repositories: repo-0 repo-1 repo-2
DEBUG util.py:445:  Updating metadata for 'repo-0'...done
DEBUG util.py:445:  error: Updating rpm-md repo 'repo-0': cannot update repo 'repo-0': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://kojipkgs.fedoraproject.org/compose/branched/latest-Fedora-36/compose/Everything/x86_64/os/repodata/repomd.xml (IP: 10.3.163.77)
DEBUG util.py:445:  Traceback (most recent call last):
DEBUG util.py:445:    File "/usr/bin/pungi-make-ostree", line 33, in <module>
DEBUG util.py:445:      sys.exit(load_entry_point('pungi==4.3.5', 'console_scripts', 'pungi-make-ostree')())
DEBUG util.py:445:    File "/usr/lib/python3.10/site-packages/pungi/ostree/__init__.py", line 159, in main
DEBUG util.py:445:      func()
DEBUG util.py:445:    File "/usr/lib/python3.10/site-packages/pungi/ostree/tree.py", line 151, in run
DEBUG util.py:445:      self._make_tree()
DEBUG util.py:445:    File "/usr/lib/python3.10/site-packages/pungi/ostree/tree.py", line 59, in _make_tree
DEBUG util.py:445:      shortcuts.run(
DEBUG util.py:445:    File "/usr/lib/python3.10/site-packages/kobo/shortcuts.py", line 409, in run
DEBUG util.py:445:      raise exc
DEBUG util.py:445:  RuntimeError: ERROR running command: rpm-ostree compose tree --repo=/mnt/koji/compose/ostree/repo --write-commitid-to=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4/commitid.log --touch-if-changed=/mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4/commitid.log.stamp --add-metadata-string=version=36.20220817.0 /mnt/koji/compose/updates/Fedora-36-updates-20220817.0/work/ostree-4/config_repo/fedora-kinoite.json
DEBUG util.py:445:  For more details see /mnt/koji/compose/updates/Fedora-36-updates-20220817.0/logs/x86_64/Everything/ostree-4/create-ostree-repo.log
```

**Comment by travier** [comment]
This happening: https://pagure.io/releng/failed-composes/issue/3868. Will open an issue.

**Comment by travier** [comment]
Closing this one as this is apparently Kinoite specific for an unknown reason
