### ISSUE TITLE
rpm-ostree commands return RUST_BACKTRACE after running post scripts

### ISSUE THREAD

**Issue by CleoMenezesJr** [fedora-silverblue/issue-tracker#433]
**Describe the bug**
When using rpm-ostree, it always returns after the post script the following: 
```
thread 'tokio-runtime-worker' panicked at 'assertion failed: !(self.ptype == ProgressType::Task)', rust/src/console_progress.rs:124:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce**
Please describe the steps needed to reproduce the bug:
1. run `rpm-ostree` something

**Expected behavior**
No Rust loga

**Screenshots**
![image](https://user-images.githubusercontent.com/54215258/225680199-05743b38-c869-4e13-99cf-eea355640225.png)

**OS version:**
```
● fedora:fedora/38/x86_64/testing/silverblue
                  Version: 38.20230314.0 (2023-03-14T01:56:13Z)
               BaseCommit: 768e4f7f68468e0101a03e6138e03e2d377090019f2013e23014ce9179c585fd
             GPGSignature: Valid signature by 6A51BBABBA3D5467B6171221809A8D7CEB10B464
      RemovedBasePackages: gnome-terminal-nautilus gnome-terminal 3.47.92-1.fc38
          LayeredPackages: akmod-nvidia dnf-plugins-core egl-gbm egl-wayland epson-inkjet-printer-escpr flatpak-builder flatpak-spawn git gnome-backgrounds-extras gnome-console
                           gnome-tweak-tool gstreamer-plugins-espeak gstreamer1-plugin-openh264 kernel-devel kernel-devel-matched langpacks-core-en langpacks-core-pt_BR langpacks-en
                           langpacks-es langpacks-pt_BR libva-utils libva-vdpau-driver nvidia-vaapi-driver podman-compose podman-docker sassc unrar vdpauinfo xorg-x11-drv-nvidia
                           xorg-x11-drv-nvidia-cuda xorg-x11-drv-nvidia-cuda-libs xorg-x11-drv-nvidia-power zsh

```

**Comment by travier** [comment]
The content of that screenshot in text format would be great. Thanks

**Comment by CleoMenezesJr** [comment]
```
❯ RUST_BACKTRACE=1 rpm-ostree update
2 metadata, 0 content objects fetched; 788 B transferred in 3 seconds; 0 bytes content written
Checking out tree 74d58a1... done
Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates-testing-modular updates-testing updates fedora rpmfusion-nonfree-nvidia-driver updates-archive
Importing rpm-md... done
rpm-md repo 'fedora-cisco-openh264' (cached); generated: 2023-03-14T10:56:46Z solvables: 4
rpm-md repo 'fedora-modular' (cached); generated: 2023-03-20T09:14:56Z solvables: 1082
rpm-md repo 'updates-modular' (cached); generated: 2018-02-20T19:18:14Z solvables: 0
rpm-md repo 'updates-testing-modular' (cached); generated: 2018-02-20T19:18:14Z solvables: 0
rpm-md repo 'updates-testing' (cached); generated: 2023-03-21T01:29:22Z solvables: 9855
rpm-md repo 'updates' (cached); generated: 2018-02-20T19:18:14Z solvables: 0
rpm-md repo 'fedora' (cached); generated: 2023-03-20T09:21:51Z solvables: 68998
rpm-md repo 'rpmfusion-nonfree-nvidia-driver' (cached); generated: 2023-03-18T12:48:33Z solvables: 30
rpm-md repo 'updates-archive' (cached); generated: 2022-11-11T05:17:33Z solvables: 0
Resolving dependencies... done
No upgrade available.

```

**Comment by Akamun** [comment]
I am facing the same error when I try to update. I am on f38 branch. `RUST_BACKTRACE=1` did not give any new output. So I tried with `RUST_BACKTRACE=full`. Here is the output:
```
RUST_BACKTRACE=full rpm-ostree upgrade
note: automatic updates (stage) are enabled
⠓ Receiving objects; 98% (2609/2662) 889.6 kB/s 500.0 MB                                                                            Enabled rpm-md repositories: fedora-cisco-openh264 fedora-modular updates-modular updates-testing-modular updates-testing updates fedora rpmfusion-free-updates-testing rpmfusion-free rpmfusion-nonfree-updates-testing rpmfusion-nonfree phracek-PyCharm rpmfusion-nonfree-nvidia-driver rpmfusion-nonfree-steam google-chrome copr:copr.fedorainfracloud.org:vstanek:gnome-info-collect updates-archive
⠋ Receiving objects; 98% (2609/2662) 889.6 kB/s 500.0 MB                                                                            thread 'tokio-runtime-worker' panicked at 'assertion failed: !(self.ptype == ProgressType::Task)', rust/src/console_progress.rs:124:9
stack backtrace:
   0:     0x562b65b70b3a - <unknown>
   1:     0x562b65b99f7e - <unknown>
   2:     0x562b65b69375 - <unknown>
   3:     0x562b65b70905 - <unknown>
   4:     0x562b65b7204f - <unknown>
   5:     0x562b65b71d8b - <unknown>
   6:     0x562b65b7275c - <unknown>
   7:     0x562b65b724b2 - <unknown>
   8:     0x562b65b70fec - <unknown>
   9:     0x562b65b72202 - <unknown>
  10:     0x562b65355ba3 - <unknown>
  11:     0x562b65355c7d - <unknown>
  12:     0x562b6580c015 - <unknown>
  13:     0x562b6548232f - <unknown>
  14:     0x7fe9984303c2 - g_closure_invoke
  15:     0x7fe99845f4f8 - <unknown>
  16:     0x7fe99844ebea - g_signal_emit_valist
  17:     0x7fe99844ee13 - g_signal_emit
  18:     0x7fe99859a90b - <unknown>
  19:     0x7fe998586210 - <unknown>
  20:     0x7fe99832b9ed - <unknown>
  21:     0x7fe99832f788 - g_main_context_dispatch
  22:     0x7fe99838ddd8 - <unknown>
  23:     0x7fe99832ee8f - g_main_loop_run
  24:     0x562b6548051a - <unknown>
  25:     0x562b65473460 - <unknown>
  26:     0x562b65477176 - <unknown>
  27:     0x562b65470d54 - <unknown>
  28:     0x562b655b646c - <unknown>
  29:     0x562b6541f3f7 - <unknown>
  30:     0x562b6546d872 - <unknown>
  31:     0x562b65acc009 - <unknown>
  32:     0x562b65abcf4b - <unknown>
  33:     0x562b65ac9f1a - <unknown>
  34:     0x562b65b78ae3 - <unknown>
  35:     0x7fe997666c57 - start_thread
  36:     0x7fe9976eca70 - __clone3
  37:                0x0 - <unknown>
Aborted (core dumped)
```

**Comment by Froggy232** [comment]
Same problem here, I have this error very often.

**Comment by summersk** [comment]
FYI @travier looks like rpm-ostree 2023.4 has the bulk of the fix for this (https://github.com/coreos/rpm-ostree/issues/4284#issuecomment-1553498420)

**Comment by travier** [comment]
Thanks! Closing now that this is fixed
