### ISSUE TITLE
F39 Rawhide python issue.

### ISSUE THREAD

**Issue by coz** [fedora-silverblue/issue-tracker#481]
[coz@fedora ~]$ fusion-icon
 * Detected Session: mate
 * Searching for installed applications...
python3: /usr/include/python3.12/object.h:215: Py_SIZE: Assertion `ob->ob_type != &PyLong_Type' failed.
Aborted (core dumped)
[coz@fedora ~]$ bleachbit
Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 43, in <module>
    import bleachbit.GUI
  File "/usr/share/bleachbit/__init__.py", line 33, in <module>
    from configparser import RawConfigParser, NoOptionError, SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/lib64/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
[coz@fedora ~]$ blender
bash: blender: command not found
[coz@fedora ~]$ sudo dnf install blender
[sudo] password for coz: 
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
Problem: conflicting requests
  - nothing provides libboost_python311.so.1.81.0()(64bit) needed by blender-1:3.6.0-1.fc39.x86_64
[coz@fedora ~]$ 
 Consistent with current upgrade as of July 10, 2023

**Comment by travier** [comment]
As I said in https://github.com/fedora-silverblue/issue-tracker/issues/479#issuecomment-1626995824, please report issue following a template.

This is also the tracker for Silverblue issues. This does not look like a Silverblue issue. Please ask for help on the Fedora discussion forums: https://discussion.fedoraproject.org/c/ask/6/none
